<?php

namespace Samuelpouzet\RestfulAuth\Controller;

use Laminas\View\Model\JsonModel;
use Samuelpouzet\Restful\Controller\AbstractRestfulController;
use Samuelpouzet\RestfulAuth\Interface\LoginInterface;

class LoginController extends AbstractRestfulController implements LoginInterface
{
    public function postAction(): JsonModel
    {
        die('test');
        return parent::postAction(); // TODO: Change the autogenerated stub
    }
}
